---
title: "Music"
output:
  html_document:
    df_print: paged
---



```{r}
library(DBI)
library(RSQLite)
library(dplyr)
#make sure you get the sqlite file here
con <- dbConnect(SQLite(), "Attachment_1645043751.sqlite")
# Show List of Tables
as.data.frame(dbListTables(con))

```
```{r}
# Get table
album<- dbReadTable(con, 'Album')
artist<- dbReadTable(con, 'Artist')
tracks<- dbReadTable(con, 'Track')
genre<- dbReadTable(con, 'Genre')
# data is fetched so disconnect it.
dbDisconnect(con)
```
#1
```{r}

left_join(tracks, album, 
              by = c("AlbumId" = "AlbumId"))  %>% group_by(ArtistId)  %>% count(ArtistId) %>% arrange(desc(n))

```
#2

```{r}
left_join(genre, tracks, 
              by = c("GenreId" = "GenreId")) %>% count(Name.x)
```
#3
```{r}
# Fit the model
model <- glm( diabetes ~., data = train.data, family = binomial)
# Summarize the model
summary(model)
# Make predictions
probabilities <- model %>% predict(test.data, type = "response")
predicted.classes <- ifelse(probabilities > 0.5, "pos", "neg")
# Model accuracy
mean(predicted.classes == test.data$diabetes)
Simple logistic regression
```
#4
```{r}
yelp <- "https://api.yelp.com"
term <- "Where is the best italian food in kalamazoo,MI?"
location <- "Kalamazoo"
categories <- NULL
limit <- 50
radius <- 8800
url <- modify_url(yelp, path = c("v3", "businesses", "search"),
                  query = list(term = term, location = location, 
                               limit = limit,
                               radius = radius))
res <- GET(url, add_headers('Authorization' = paste("bearer", client_secret)))

results <- content(res)

yelp_httr_parse <- function(x) {

  parse_list <- list(id = x$id, 
                     name = x$name, 
                     rating = x$rating, 
                     review_count = x$review_count, 
                     latitude = x$coordinates$latitude, 
                     longitude = x$coordinates$longitude, 
                     address1 = x$location$address1, 
                     city = x$location$city, 
                     state = x$location$state, 
                     distance = x$distance)
  
  parse_list <- lapply(parse_list, FUN = function(x) ifelse(is.null(x), "", x))
  
  df <- data_frame(id=parse_list$id,
                   name=parse_list$name, 
                   rating = parse_list$rating, 
                   review_count = parse_list$review_count, 
                   latitude=parse_list$latitude, 
                   longitude = parse_list$longitude, 
                   address1 = parse_list$address1, 
                   city = parse_list$city, 
                   state = parse_list$state, 
                   distance= parse_list$distance)
  df
}

results_list <- lapply(results$businesses, FUN = yelp_httr_parse)

business_data <- do.call("rbind", results_list)

```



